services:
  trustflow-envoy:
    image: secretflow/trustflow-envoy-ubuntu22.04:0.1.0b0
    volumes:
      - type: bind
        source: ./envoy
        target: /envoy
      - type: bind
        source: ./shared
        target: /shared
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: /home/trustflow_envoy/envoy -c /envoy/envoy.yml --log-path /shared/log/envoy.log
    healthcheck:
     test: ["CMD", "curl", "-f", "-X", "POST", "http://127.0.0.1:9901/healthcheck/ok"]
     interval: 30s
     timeout: 10s
     retries: 3
     start_period: 30s
    ports:
      - 50001:50001

  ra-proxy:
    image: secretflow/trustflow-ra-proxy-tdx-ubuntu22.04:0.1.0b0
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    devices:
      - /dev/tdx_guest:/dev/tdx_guest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: >
      /home/trustflow/proxy/ra_proxy/main 
      --cert_path /shared/deploy/carol.crt 
      --plat tdx 
      --port 50002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:50002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - trustflow-envoy

  teeapp:
    image: secretflow/trustflow-release-ubuntu22.04:latest
    volumes:
      - type: bind
        source: ./teeapp
        target: /teeapp
      - type: bind
        source: ./shared
        target: /shared
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: >
      bash -c "
      export PATH=/root/miniconda3/bin:$PATH &&
      pip install -r /teeapp/requirements.txt &&
      python3 /teeapp/demo_http_server.py --port 8000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "http://127.0.0.1:8000/teeapp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - trustflow-envoy