
services:
  data-capsule-proxy:
    image: secretflow/trustflow-data-capsule-proxy-tdx-ubuntu22.04:0.1.0b0
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    devices:
      - /dev/tdx_guest:/dev/tdx_guest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: > 
      /home/trustflow/proxy/data_capsule_proxy/main 
      --cert-path /shared/deploy/carol.crt 
      --private_key_path /shared/deploy/carol.key 
      --plat tdx
      --port 50003
      --log_path /shared/log/data-capsule-proxy.log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:50003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks: 
      offline_network:
        ipv4_address: 172.31.9.10

  teeapp:
    image: secretflow/trustflow-release-ubuntu22.04:latest
    volumes:
      - type: bind
        source: ./teeapp
        target: /teeapp
      - type: bind
        source: ./shared
        target: /shared
    environment:
      - TZ=Asia/Shanghai
    command: >
      bash -c "
      export PATH=/root/miniconda3/bin:$PATH &&
      pip install -r /teeapp/requirements.txt &&
      python3 /teeapp/psi.py
      "
    networks: 
      offline_network:
        ipv4_address: 172.31.9.11
    depends_on:
      - data-capsule-proxy

networks:
  offline_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.9.0/24